### ISSUE TITLE
Place "Virtual" as City is displayed as being in Bologna

### ISSUE THREAD

**Issue by hauschke** [SmartDataAnalytics/OpenResearch#219] opened 2021-04-26 10:15 UTC
![grafik](https://user-images.githubusercontent.com/1275231/116066821-c1ac7500-a688-11eb-831d-1f57d46b32dd.png)

Example: https://confident.dbis.rwth-aachen.de/or/index.php?title=FABRICATE_2020

**Comment by WolfgangFahl** [comment] 2021-04-26 10:49
Duplicate of #209

**Closed by WolfgangFahl** 2021-04-26 10:49 UTC

**Comment by WolfgangFahl** [comment] 2021-04-26 10:54
"Online" is fed into #geocode of the https://www.mediawiki.org/wiki/Extension:Maps which in turn calls the configured geocoding service. The result is directly put into https://confident.dbis.rwth-aachen.de/or/index.php?title=Property:Has_coordinates without checking whether the result is o.k. The base problem is exactly the one outlined in the Migration Plan summary. 

Worse - the design of the approach is flawed since the geocoding is done redudantly for each event instead of getting the geocode result for a venue once and reusing it for all events happening at that venue. For each and every template change currently some 10.000 API geocoding calls are fired and we end up our quota with the service being exceeded.
